wageauction/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
import random
from django import forms
import time
import datetime

from django.db import models as djmodels

author = 'Essi Kujansuu, EUI, essi.kujansuu@eui.eu, adapting work of Philipp Chapkovski, UZH, chapkovski@gmail.com'

doc = """
Adaptation of Fehr et al. 1993 auction.
"""


class Constants(BaseConstants):
    name_in_url = 'wageauction'
    players_per_group = 5
    num_rounds = 2
    starting_time = 15000
    num_employers = 2
    num_workers = players_per_group - num_employers
    assert num_workers > num_employers, 'NUMBER OF EMPLOYERS SHOULD EXCEED THE NUMBER OF WORKERS IN THE MARKET'
    task_time = 300
    lb = 30
    ub = 101
    step = 5
    offers = list(range(lb, ub, step))


class Subsession(BaseSubsession):
    wp_to_delete_completion=models.IntegerField()
    def creating_session(self):
        tax_outcome = random.randint(1, 3)
        for p in self.get_players():
            p.tax_outcome = tax_outcome


class Group(BaseGroup):
    auctionenddate = models.FloatField()
    day_over = models.BooleanField()

    def time_left(self):
        now = time.time()
        time_left = self.auctionenddate - now
        time_left = round(time_left) if time_left > 0 else 0
        return time_left

    def set_payoffs(self):
        # TO DO: the payoff function should be re-written completely based on new JobCOntract model info - Philipp
        for person in self.get_players():
            if person.role() == 'employer':
                if person.partner_id == 0:
                    person.payoff = 0
                else:
                    if person.tax_outcome == 2:
                        person.payoff = 40 - (
                            person.wage_offer + person.wage_adjustment) + 0.8 * 20 * person.tasks_correct
                    else:
                        person.payoff = 40 - (person.wage_offer + person.wage_adjustment) + 20 * person.tasks_correct
            if person.role() == 'worker':
                if person.partner_id == 0:
                    person.payoff = 20
                else:
                    if person.tax_outcome == 3:
                        person.payoff = 0.8 * (person.wage_offer + person.wage_adjustment)
                    else:
                        person.payoff = (person.wage_offer + person.wage_adjustment)


class Player(BasePlayer):
    wage_offer = models.IntegerField()
    tax_outcome = models.PositiveIntegerField()
    wage_adjustment = models.IntegerField()
    wage_adjusted=models.IntegerField()
    last_correct_answer=models.IntegerField()
    tasks_attempted = models.PositiveIntegerField(initial=0)
    tasks_correct = models.PositiveIntegerField(initial=0)
    partner_payoff = models.CurrencyField()
    active_worker=models.BooleanField()
    job_to_do_updated=models.BooleanField(initial=False)

    def role(self):
        if self.id_in_group <= Constants.num_employers:
            return 'employer'
        if self.id_in_group > Constants.num_employers:
            return 'worker'


class Request(djmodels.Model):
    employer = djmodels.ForeignKey(Player, related_name='requests')
    amount = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class JobContract(djmodels.Model):
    employer = djmodels.ForeignKey(Player, related_name='contract', unique=True)
    worker = djmodels.ForeignKey(Player, blank=True, null=True, related_name='work_to_do')
    amount = models.IntegerField()
    accepted = models.BooleanField()
    amount_updated = models.IntegerField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

wageauction/_builtin/__init__.py
# This file is auto-generated.
# It's used to aid autocompletion in code editors.

import otree.api
from .. import models


class Page(otree.api.Page):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.api.Bot):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

wageauction/views.py
from otree.api import Currency as c, currency_range
from . import models
from ._builtin import Page, WaitPage
from .models import Constants, Group, Subsession, JobContract
import time
from random import randint
from channels import Group as ChannelGroup
from otree.models_concrete import CompletedGroupWaitPage


class EmployerPage(Page):
    def is_displayed(self):
        return self.player.role() == 'employer' and self.extra_is_displayed()

    def extra_is_displayed(self):
        return True


class WorkerPage(Page):
    def is_displayed(self):
        return self.player.role() == 'worker' and self.extra_is_displayed()

    def extra_is_displayed(self):
        return True


class ActiveWorkerPage(Page):
    def is_displayed(self):
        return self.player.role() == 'worker' and self.player.active_worker and self.extra_is_displayed()

    def extra_is_displayed(self):
        return True


class WP(WaitPage):
    def after_all_players_arrive(self):
        now = time.time()
        self.group.auctionenddate = now + Constants.starting_time


class Auction(EmployerPage):
    def extra_is_displayed(self):
        closed_contract = self.player.contract.filter(accepted=True).exists()
        return not any([self.group.day_over, closed_contract])

    def vars_for_template(self):
        active_contracts = JobContract.objects.filter(accepted=False, employer__group=self.group)
        return {'time_left': self.group.time_left(),
                'active_contracts': active_contracts,
                }

    def before_next_page(self):
        closed_contract = self.player.contract.filter(accepted=True)
        if closed_contract.exists():
            self.player.wage_offer = closed_contract.first().amount


class Accept(WorkerPage):
    def extra_is_displayed(self):
        closed_contract = self.player.work_to_do.filter(accepted=True).exists()
        return not any([self.group.day_over, closed_contract])

    def vars_for_template(self):
        active_contracts = JobContract.objects.filter(accepted=False, employer__group=self.group).values('pk', 'amount')
        return {'time_left': self.group.time_left(),
                'active_contracts': active_contracts}

    def before_next_page(self):
        closed_contract = self.player.work_to_do.filter(accepted=True).exists()
        self.player.active_worker = closed_contract


class AfterAuctionDecision(EmployerPage):
    form_model = models.Player
    form_fields = ["wage_adjusted"]

    def extra_is_displayed(self):
        closed_contract = self.player.contract.filter(accepted=True).exists()
        return closed_contract

    def before_next_page(self):
        closed_contract = self.player.contract.get(accepted=True)
        closed_contract.amount_updated = self.player.wage_adjusted
        closed_contract.save()
        closed_contract.worker.job_to_do_updated = True


class AuctionResultsEmployer(EmployerPage):
    ...


class ActiveWorkerWPBeforeStart(WaitPage):
    def is_displayed(self):
        self.subsession.wp_to_delete_completion = self._index_in_pages
        if self.player.role() == 'employer':
            closed_contract = self.player.contract.filter(accepted=True)
            if closed_contract.exists():
                worker_pk = self.player.contract.get().worker.participant.pk
                self.send_completion_message(set([worker_pk]))

        return (not self.player.job_to_do_updated) and self.player.active_worker


class AuctionResultsWorker(ActiveWorkerPage):
    def vars_for_template(self):
        completion = CompletedGroupWaitPage.objects.filter(
            page_index=self.subsession.wp_to_delete_completion,
            id_in_subsession=self.group.id_in_subsession,
            session=self.session,
        )
        if completion.exists():
            completion.delete()
        closed_contract = self.player.work_to_do.get()
        worker_wage_offer = closed_contract.amount
        worker_wage_adjusted = closed_contract.amount_updated
        return {'worker_wage_offer': worker_wage_offer,
                'worker_wage_adjusted': worker_wage_adjusted, }


class Start(ActiveWorkerPage):
    ...


class WorkPage(ActiveWorkerPage):
    timer_text = 'Time left to complete this section:'

    timeout_seconds = 30000

    def before_next_page(self):
        ...


class WaitP(WaitPage):
    def after_all_players_arrive(self):
        self.group.set_payoffs()


class Results(Page):
    ...


page_sequence = [
    WP,
    Auction, Accept,
    AfterAuctionDecision,
    AuctionResultsEmployer,
    ActiveWorkerWPBeforeStart,
    AuctionResultsWorker,
    Start,
    WorkPage,
    WaitP,
    Results
]

wageauction/templates/wageauction/Accept.html
{% extends "wageauction/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Auction
{% endblock %}

{% block content %}
    AAA {{ group.pk }}
    <div class="instructions well well-lg">
        <p>
            There are <b> <span id="emps_left"> {{ Constants.num_employers }} </span> </b> employers and <b><span
                id="workers_left"> {{ Constants.num_workers }} </span> </b> workers left in the market.
        </p>
        <p>
            To accepted an offer, click one of the standing offers and then "Accept". <br>
            The "Accept" button will appear after an offer has been clicked. </p>
        <p> This is the initial wage offer.
            Your payoff for this round will consist of the final wage, minus some potential taxes announced later. </p>
    </div>

    <div id="otree-timeout">Time left to the end of the auction:
        <span id="otree-timer__time-left"></span></div>
    <br>
    {% include 'wageauction/open_contracts_block.html' %}
{% endblock %}


{% block scripts %}
    <script type="text/javascript" src="{% static "wageauction/js/jquery.countdown.js" %}"></script>
    {% include 'wageauction/js_vars_for_auction_block.html' %}
    <script>
        $(document).on('click', '.open_contract', function () {
           accept_contract($(this).data('pk'));
        });
        accept_contract = function (contract) {

            var msg = {
                role: role,
                player_pk: player_pk,
                contract_to_accept: contract
            };
            if (socket.readyState === socket.OPEN) {
                socket.send(JSON.stringify(msg));
            }
            ;
        };
    </script>
{% endblock %}

wageauction/templates/wageauction/AfterAuctionDecision.html
{% extends "wageauction/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Results of the auction
{% endblock %}

{% block content %}
    AAA {{ form.wage_adjusted.errors }}
    <div id="some-name">
        <p>
            In stage 1, <span id="status"> </span>
            <span id="wage"> </span><span id="last"> <b>{{ player.wage_offer }}</b>. </span>
        </p>
    </div>
    <div>
        <h3> Tax conditions </h3>
        <p>
            <span id="tax_condition"> </span>
        </p>
    </div>


    <div>
        <h3> Potential adjustment </h3>

        <span id="replace">
<p>
    The wage offer is preliminary. As an employer, you must choose the final wage.
</p>
<p>
    You can chose the final wage by clicking the appropriate button and then submitting.
</p>
<p>
    Your <b>initial wage of {{ player.wage_offer }}</b> is marked with the <b><span
        class="chosenbutton">light blue</span></b> background colour.
</p>
    </span>
    </div>
    <span id="hide">
    <p>You can offer: </p>
    </span>

    <span id="adjustmentoptions">
            {% for offer in Constants.offers %}
                <button type="button" data-offer={{ offer }} class="offer
                        {% if offer == player.wage_offer %}
                        chosenbutton
                        {% endif %}">
                {{ offer }}
                </button>
            {% endfor %}

        <p>Submit the final wage by clicking "submit": </p>
            </span>
    <input type="number" id="to_show_adjusted" value={{ player.wage_offer }} class="offer"
           style="background-color:white">
    <input type="hidden" name='wage_adjusted' id="id_wage_adjusted" value={{ player.wage_offer }}>

    <input type="submit" id="submit_button" value="Submit" class="offer">


    </div>
    </p>
    </div>

{% endblock %}

{% block styles %}

    <!-- define a style -->
    <style type="text/css">
        .chosenbutton {
            background-color: lightskyblue;
            color: navy;
            padding: 2px 10px 2px 10px;
            border: groove;
            border-color: lightsteelblue;
            font-weight: bold;
            margin: 1px;
        }
    </style>

{% endblock %}


{% block scripts %}
    <script>
        $("button.offer").on("click", function () {
            var adjusted_offer = $(this).data('offer');
            $('input#to_show_adjusted').val(adjusted_offer);
            $('input#id_wage_adjusted').val(adjusted_offer);
        });
    </script>
{% endblock %}

wageauction/templates/wageauction/Auction.html
{% extends "wageauction/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Auction
{% endblock %}

{% block content %}

    <div class="instructions well well-lg">
        <p> To offer an initial wage to the potential employees, click one of the buttons below and then submit. <br>
            (The submit button will appear after clicking a number button.) <br>
            All offers will be communicated to the workers and other employers still participating in the auction.
        </p>
        <p>
            There are <b> <span id="emps_left"> {{ Constants.num_employers }} </span> </b> employers and <b><span
                id="workers_left"> {{ Constants.num_workers }} </span> </b> workers left in the market.
        </p>
        <p>
            If you hire a worker, you are endowed with 40 points but you have to pay the final wage out of this (and
            some potential revenue).
            If you do not hire any worker, your payoff is 0. Taxes may apply. </p>
    </div>

    <div id="otree-timeout">Time left to the end of the auction:
        <span id="otree-timer__time-left"></span></div>

    {% include 'wageauction/open_contracts_block.html' %}

    <div> Your current wage offer: <b><span id="standing_offer"></span></b></div>
    <div>
        <p>You can offer:
            {% for offer in Constants.offers %}
                <button type="button" data-offer={{ offer }} class="offer">{{ offer }}</button>
            {% endfor %}
        </p>
    </div>
{% endblock %}


{% block scripts %}
    <script type="text/javascript" src="{% static "wageauction/js/jquery.countdown.js" %}"></script>
    {% include 'wageauction/js_vars_for_auction_block.html' %}
    <script>
        $("button.offer").on("click", function () {
            console.log('offer clicked');
            create_or_update_contract($(this).data('offer'));
        });
        create_or_update_contract = function (amount) {
            var msg = {
                role: role,
                player_pk: player_pk,
                wage_offer: amount
            };
            if (socket.readyState === socket.OPEN) {
                socket.send(JSON.stringify(msg));
            }
            ;
        };
    </script>
{% endblock %}

wageauction/templates/wageauction/AuctionResultsEmployer.html
{% extends "wageauction/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Results of the auction {{ player.round_number }}
{% endblock %}

{% block content %}

<div id="some-name">
<p>
    In the first stage, <span id="status"> </span>
</p>
</div>

<div>
<p>
    <span id = "tax_condition"> </span>
</p>
</div>


<div>
    <span id="adjustment_info">
<p>
    The initial wage offer was <b>{{ player.wage_offer }}</b>.
</p>
    <p>
    You chose the final wage: <b> <span id="final"> {{ player.wage_adjusted }}</span> </b>.
</p>
    </span>
    </div> <br>

<div>
    <p>
            In the next stage the workers hired will have 5 minutes for the counting task. <br>
    </p>

</div>
    {% next_button %}
{% endblock %}

wageauction/templates/wageauction/AuctionResultsWait.html
{% extends 'otree/WaitPage.html' %}
{% load staticfiles otree_tags %}
{% block title %}
    {{ title_text }}
{% endblock %}
{% block content %}

<div>
<span id="header"> <h2> Tax conditions </h2> </span>
<p>
<span id="tax_condition"></span>
</p>
</div>


{% endblock %}

{% block scripts %}
    <script>
        var taxcond = {{ player.tax_outcome |json }};
        var role = {{ participant.id_in_session |json }};
        var notax = "There are no unforeseen taxes this period.";
        var firmtax = "A tax of 20 % on firm revenue will implemented.";
        var workertax = "A tax of 20 % on worker earnings will implemented.";
        var na_worker = "You were not hired in this round. You will continue when the next round starts.";
        var na_employer = "You did not hire a worker this round. You will continue when the next round starts.";


        window.onload = function () {
            if (role > {{ Constants.num_employers }}) {
                // If hired worker:
                if (0 < {{ player.partner_id }}) {
                    if (taxcond === 1) {
                        $('span#tax_condition').html(notax);
                    }
                    else if (taxcond === 2) {
                        $('span#tax_condition').html(firmtax);
                    }
                    else if (taxcond === 3) {
                        $('span#tax_condition').html(workertax);
                    }
                    else {
                        $('span#tax_condition').html(na);
                    }
                }
                // If unemployed worker
                else {
                    $('span#tax_condition').html(na_worker);
                    $('span#header').empty();
                }
            }
                // if an employer, hiring
            else {
                if (0 < {{ player.partner_id }}) {
                    $('span#header').empty();
                    $("span#tax_condition").html("Your decision has been recorded, waiting for other players.");
                }
                // if employer unmatched
                else {
                    $('span#tax_condition').html(na_employer);
                    $('span#header').empty();
                }
            }
        }

    </script>

{% endblock %}

wageauction/templates/wageauction/AuctionResultsWorker.html
{% extends "wageauction/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Results of the auction {{ player.round_number }}
{% endblock %}

{% block content %}
<div>
<p>
    In the first stage, <span id="status">.</span>
</p>
</div>
<div>
<p>
    <span id = "tax_condition"> </span>
</p>
</div>

<div>
    <span id="adjustment_info">
<p>
    The employer that hired you was given the change to adjust the wage.
</p>
    <p>
        The initial wage offer was <b>{{ worker_wage_offer }}</b>.
        </p>
    <p>
    The final wage is <b><span id="final"> {{ worker_wage_adjusted }} </span></b>.
</p>
        </span>
</div> <br>
<div>
    <p>
            In the next stage the workers that have been hired will have 5 minutes for the counting task.
    </p>

</div>
    {% next_button %}

{% endblock %}

{% block scripts %}

{% endblock %}

wageauction/templates/wageauction/Page.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block app_styles %}

    <style type="text/css">
        .otree-title {
            background-color: steelblue;
            color: white;
            margin: 10px 0 10px 0;
            padding: 20px;
        }

        .otree-timer {
            background: lightsteelblue;
            color: white;
            border-color: white;
        }

        .otree-body {
            text-indent: each-line;
        }

        .box-heading {
            background-color: steelblue;
            color: white;
            margin: 10px 10px 10px 10px;
            padding: 10px 10px 10px 24px;
        }

        .table-style {
            color: black;
            margin: 10px 10px 10px 10px;
        }

        .table-borders {
            border: solid;
            border: steelblue;
            background-color: #ecf2f9;
            align-content: center;

        }

        .offer {
            background-color: whitesmoke;
            color: navy;
            padding: 1px 10px 1px 10px;
            border: groove;
            border-color: lightsteelblue;
            font-weight: bold;
            margin: 1px;
        }

        .otree-btn-next {
            background-color: steelblue;
            color: white;
            padding: 5px 10px 5px 10px;

        }

        h2, h3, h4, h5, h6 {
            font-weight: bolder;
            color: #24435c;
        }

    </style>

{% endblock %}

wageauction/templates/wageauction/Results.html
{% extends "wageauction/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Results of round {{ player.round_number }}
{% endblock %}

{% block content %}

    <span id="status"> You were <b>hired</b> this round. You </span>

    <span id="task_results">tried <b>{{ player.tasks_attempted }}</b> tasks,
        of which <b>{{ player.tasks_correct }}</b> were correct. <br>
        Each correct task is worth <b> <span id="task_revenue">20</span> </b> points to the employer <span id="revenue_tax">.</span> <br> <br>
    </span>

    <span id="wage_results">
    The final wage is <b><span id="final_wage"> </span></b>. <br>
    <span id="wage_tax"> <br> </span>
    </span>

    <span id="no_taxes"> </span>

    Your payoff this round is <b>{{ player.payoff }}</b>.
    <span id="your_breakdown"> </span> <br>

    <span id="no_partner"> Your partner's payoff is <b>{{ player.partner_payoff }}</b>.</span>
    <span id="partners_breakdown"> <span id="final_wage"> </span> - 0.2 * <span id="final_wage"> </span> </span><br>

    {% next_button %}
{% endblock %}

{% block scripts %}
    <script>

    var employee = "You <b>hired a worker</b> this round and this worker";
    var role = {{ participant.id_in_session |safe }};
    var taxcond = {{ player.tax_outcome |json }};
    var unemployed = "You were not matched this round. <br><br>";
    var final_wage = {{ player.wage_offer|json }} + {{ player.wage_adjustment|json }};


    var notax = "There were <b>no unforeseen taxes</b> this period.<br><br>";
    var workertax = "A <b>tax of 20 % on worker earnings</b> is implemented.<br><br>";
    var employer_breakdown = "That is 40 + 20 * {{ player.tasks_correct|json }} - " + final_wage + "." ;
    var employer_tax = "That is 40 + 16 * {{ player.tasks_correct|json }} - " + final_wage + ".";
    var worker_tax = "It is the final wage " + final_wage + " less the taxes 0.2 * " + final_wage + " = " + (final_wage * 0.2);
    var worker_breakdown = "It consists entirely of the final wage.";

    window.onload = function () {
        // If not matched: super simple.
        if (0 < {{ player.partner_id|json }}) {
            $('span#final_wage').html(final_wage);
            // If a employer
            if (role < {{ Constants.num_employers|json }} +1) {
                // In general
                $('span#status').html(employee);

                // Under different tax conditions
                if (taxcond === 1) {
                    $('span#your_breakdown').html(employer_breakdown);
                    $('span#partners_breakdown').html(worker_breakdown);
                    $('span#no_taxes').html(notax);
                }
                else if (taxcond === 2) {
                    $('span#your_breakdown').html(employer_tax);
                    $('span#partners_breakdown').html(worker_breakdown);
                    $('span#revenue_tax').html(" because there is a 20 % tax on the normal revenue of 20 points per correct task.");
                    $('span#task_revenue').html(16);
                }
                else if (taxcond === 3) {
                    $('span#your_breakdown').html(employer_breakdown);
                    $('span#partners_breakdown').html(worker_tax);
                    $('span#wage_tax').html(workertax);
                }
            }
            // if a worker
            else {
                // In general

                //
                if (taxcond === 1) {
                    $('span#your_breakdown').html(worker_breakdown);
                    $('span#partners_breakdown').html(employer_breakdown);
                    $('span#no_taxes').html(notax);
                }
                else if (taxcond === 2) {
                    $('span#your_breakdown').html(worker_breakdown);
                    $('span#partners_breakdown').html(employer_tax);
                    $('span#revenue_tax').html("because there is a 20 % tax on the normal 20 points.");
                    $('span#task_revenue').html(16);

                }
                else if (taxcond === 3) {
                    $('span#your_breakdown').html(worker_tax);
                    $('span#partners_breakdown').html(employer_breakdown);
                    $('span#wage_tax').html(workertax);

                }

            }
        }
        else {
            $('span#status').html(unemployed);
            $('span#task_results').empty();
            $('span#wage_results').empty();
            $('span#no_partner').empty();
            $('span#partners_breakdown').empty();
        }
    };

    </script>
{% endblock %}

wageauction/templates/wageauction/Start.html
{% extends "wageauction/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Counting task
{% endblock %}

{% block content %}

    <p>
        The task is to <b>find the largest number in the box on the left</b> and <b>the largest number in the box on the right</b> and
        <b>add</b> these two numbers together. Submit the number in the text box.
    </p>

    <p>
        You have <b>5 minutes</b> to complete a <b>maximum of 10</b> tasks.
    </p>
    <p>
    When ready, click "Next".
    </p>

    {% next_button %}

{% endblock %}

wageauction/templates/wageauction/WPage.html
{% extends 'otree/WaitPage.html' %}
{% load staticfiles otree_tags %}
{% block title %}
    Results of the auction
    {{ title_text }}
{% endblock %}
{% block content %}
<div id="some-name">
<p>
    In stage 1, <span id="status">What ever, get rid off.</span>
    <span id="wage">And something else.</span> <b><span id="last">{{ player.wage_offer }}.</span></b>
</p>
</div>
<div>
<h2> Tax conditions </h2>
<p>
    There are no unforeseen taxes this period. / A tax on firm revenue is implemented. / A tax on worker earnings is implemented.
</p>
</div>
<p> SHOULD THIS BE A WAGE PAGE AND THEN GO TO A REAL RESULTS PAGE WITH THE ADJUSTMENTS AND SHOCKS INCLUDED. </p>

<p>
We are waiting for the employers to finalize the contracts (wages) offered.
</p>

    {% next_button %}

{% endblock %}

{% block scripts %}
    <script>
    // I'm doing it for both, but this is actually only for the workers!
        var hired = "you got <b>hired</b>";
        var unemployed = "you were not employed.";
        var offered = "and offered the wage of ";
        var partner = {{ player.partner_id |json }};

        window.onload = function () {
            if (partner === 0) {
                $('span#status').html(unemployed);
                $('span#last').empty();
                $('span#wage').empty();
            }
            else {
                $('span#status').html(hired);
                $("span#wage").html(offered);
            }
        };

    </script>
{% endblock %}

wageauction/templates/wageauction/WorkPage.html
{% extends "wageauction/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Counting task
{% endblock %}

{% block content %}

    <head>
        <style>
            th, td {
                padding: 4px 6px 4px 6px;
            }

            table#box1 {
                background-color: #ecf2f9;
            }

            table#box2 {
                background-color: #ecf2f9;
            }
        </style>
    </head>

    <p>
        Your task is to first find <b>the largest number in each of the two boxes</b> and then <b>add up the two
        numbers</b>. <br>
        Submit your answer in the box below. The correct answer is <span id="correct_answer"></span>!
    </p>

    <table style="width:100%">
        <tr>
            <th class="box-heading"> Box 1</th>
            <th></th>
            <th class="box-heading"> Box 2</th>
        </tr>
        <tr>

            <!-- NEST ANOTHER TABLE! -->
            <td class="table-borders">
                <table class="table-style" style="width:99%" id="box1">
                </table>
            </td>

            <!-- Some space -->
            <td>

            </td>
            <!-- NEST ANOTHER TABLE! -->
            <td class="table-borders">
                <table class="table-style" style="width:99%" id="box2">

                </table>
            </td>
        </tr>
    </table>
    <div>Your answer is:</div>
    <input type="number" id="answer" class="offer" style="background-color: white" required>
    <button class="answer" type="button">Answer</button>

    <p> Tasks attempted so far: <span id="tasks_attempted">{{ player.tasks_attempted }}</span></p>
    <p> Tasks correct so far: <span id="tasks_correct"> {{ player.tasks_correct }}</span></p>

{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $(window).keydown(function (event) {
                if (event.keyCode == 13) {
                    event.preventDefault();
                    return false;
                }
            });
        });
    </script>
    <script type="text/javascript" src="{% static "directauction/js/jquery.countdown.js" %}"></script>
    {% include 'wageauction/js_work_page.html' %}
    <script>
        $("button.answer").on("click", function () {
            var msg = {
                'answer': $('input#answer').val(),
            };
            if (socket.readyState === socket.OPEN) {
                socket.send(JSON.stringify(msg));
            }
            ;

        });

        $("input#answer").keyup(function (event) {
            if (event.keyCode == 13) {
                event.preventDefault();
                $("button.answer").click();
            }
        });
    </script>
{% endblock %}

wageauction/templates/wageauction/open_contracts_block.html
    <p>Standing wage offers are: </p>
    <div id="active_offers">
        {% if active_contracts %}
            {% for contract in active_contracts %}
                <span  class='badge open_contract offer' data-pk={{ contract.pk }} data-amount={{ contract.amount }} >{{ contract.amount }}</span>
            {% endfor %}
        {% else %}
            There are currently no standing offers.
        {% endif %}
    </div>

<style>
    .open_contract{
        cursor: pointer!important;
    }
</style>